name: Mobisix
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  http: '>=0.11.3+12'

  path_provider: "^0.2.1+1"

  synchronized: "^1.1.0"

  chewie: "^0.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/loading.gif
    
