name: Mobisix
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  http: '>=0.11.3+12'

  path_provider: "^0.2.1+1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
